name: auto-commit

on:
  workflow_dispatch:

  schedule:
    - cron:  "0 0 1 * *"

permissions:
  contents: write
  pull-requests: write      # 'write' access to pull requests

jobs:

  auto-commit:
    # needs: check-branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: 'checkout new branch'
        run: |
          git checkout -b ${{ env.CURRENT_DATETIME }}_auto_commit

      - name: 'Run process & Commit'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src/pages/blog
          echo "# ${{ env.CURRENT_DATETIME }}" > ${{ env.CURRENT_DATETIME }}.md
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .
          git commit -m "[add] 自動コミット:${{ env.CURRENT_DATETIME }}"
          git push origin ${{ env.CURRENT_DATETIME }}_auto_commit

      - name: 'Create Pull Request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "自動コミット:${{ env.CURRENT_DATETIME }}" --body "自動コミット:${{ env.CURRENT_DATETIME }}" --base main --head ${{ env.CURRENT_DATETIME }}_auto_commit
