name: auto-commit

on:
  workflow_dispatch:

  schedule:
    - cron:  "*/5 0 * * *"

permissions:
  contents: write
  pull-requests: write      # 'write' access to pull requests

jobs:
  # check-branch:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: 'check exist today branch'
  #       run: |
  #         git branch -a
  #         echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
  #         git branch -a | grep ${{ env.CURRENT_DATETIME }}_auto_commit
  #         if [ $? -eq 0 ]; then
  #           echo "branch exist"
  #           exit 1
  #         else
  #           echo "branch not exist"
  #         fi

  auto-commit:
    # needs: check-branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: 'checkout new branch'
        run: |
          git checkout -b ${{ env.CURRENT_DATETIME }}_auto_commit

      - name: 'Run process & Commit'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src/pages/blog
          echo "# ${{ env.CURRENT_DATETIME }}" > ${{ env.CURRENT_DATETIME }}.md
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .
          git commit -m "[add] 自動コミット:${{ env.CURRENT_DATETIME }}"
          git push origin ${{ env.CURRENT_DATETIME }}_auto_commit
      # - name: GitHub Push
      #   uses: ad-m/github-push-action@v0.8.0
      #   with:
      #     directory: "."
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Create Pull Request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "自動コミット:${{ env.CURRENT_DATETIME }}" --body "自動コミット:${{ env.CURRENT_DATETIME }}" --base main --head ${{ env.CURRENT_DATETIME }}_auto_commit
