name: auto-commit

on:
  workflow_dispatch:
    inputs:
      topic:
        description: '記事のトピックを入力してください'
        required: true
        default: 'Youtubeにおける美容トレンドはなんですか？'

  schedule:
    - cron:  "0 0 * * *"

permissions:
  contents: write
  pull-requests: write      # 'write' access to pull requests

jobs:

  auto-commit:
    # needs: check-branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: 'checkout new branch'
        run: |
          git checkout -b ${{ env.CURRENT_DATETIME }}_auto_commit

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'poetry'

      - name: Install Dependencies
        working-directory: ./article_writer
        run: poetry install --no-interaction

      - name: 'Run article_writer'
        working-directory: ./article_writer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BING_SUBSCRIPTION_KEY: ${{ secrets.BING_SUBSCRIPTION_KEY }}
          BING_SEARCH_URL: ${{ secrets.BING_SEARCH_URL }}
        # run: poetry run python main.py
        # - name: 'Run process & Commit'
        #   env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run python main.py ${{ github.event.inputs.topic }}

          # 生成したarticle_writer/articles内にあるmdファイル名を取得
          MD_FILE_NAME=$(ls articles)
          echo MD_FILE_NAME=$MD_FILE_NAME >> $GITHUB_ENV

          # 生成したmdファイルをsrc/pages/blogに移動
          echo mv articles/$MD_FILE_NAME ../src/pages/blog/
          mv articles/$MD_FILE_NAME ../src/pages/blog/

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          cd ../
          git add .
          git commit -m "[add] 自動コミット:${{ env.CURRENT_DATETIME }}-${MD_FILE_NAME}"

          git push origin ${{ env.CURRENT_DATETIME }}_auto_commit

      - name: 'Create Pull Request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "自動コミット:${{ env.CURRENT_DATETIME }}" --body "自動コミット:${{ env.CURRENT_DATETIME }}" --base main --head ${{ env.CURRENT_DATETIME }}_auto_commit
